resources:
  whats_my_ip:
    url:  "http://ip.jsontest.com/"
  date:
    url:  "http://date.jsontest.com/"
  headers:
    url: "http://headers.jsontest.com/"
  echo:
    url: "http://echo.jsontest.com/key/value/one/two"
  cookie:
    url: "http://cookie.jsontest.com/"
  md5:
    url: "http://md5.jsontest.com/?text=sometext"
  greet:
    url: "http://echo.jsontest.com/Hello/:name!"
facades:
  f1:
    strategy: merge
    resources:
      - whats_my_ip
      - date
      - headers
      - echo
      - cookie
      - md5
  greet:
    resources:
      - greet
